type: object
properties:
  initialScore:
    type: integer
    description: Initial score for the quiz taker.
  questions:
    type: array
    items:
      type: object
      properties:
        title:
          type: string
          description: The question title.
        answers:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
                description: The answer text.
              effect:
                type: integer
                description: The effect of the answer on the quiz taker's score.
      required:
        - title
        - answers
    minItems: 1
required:
  - initialScore
  - questions
